spring:

  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres
    username: postgres.gaykndiuoamjgoyxrtek
    password: 7401MsNtWogHG3PH
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true


jpa:
  properties:
    generate-ddl: true
    hibernate:
      format_sql: true
      highlight_sql: true
      use_sql_comments: true
      ddl-auto: create
      show-sql: true


logging:
  level:
    org.springframework.security: trace
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
      springframework:
        security: debug

auth:
  jwt:
    issuer: team.sparta.com
    secret: fdkiwjjfafjfilldpfnfiwdekofkhfirgrfki
    accessTokenExpiration: 168
        