spring:

  # H2 DATABASE Setting
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/test
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true


jpa:
  properties:
    hibernate:
      format_sql: true
      highlight_sql: true
      use_sql_comments: true
      ddl-auto: create
      show-sql: true

auth:
  jwt:
    issuer: team.sparta.com
    accessTokenExpireTime: 1

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
      springframework:
        security: debug